// Home
export const SET_SCROLLED_TO_TOP_SUCCESS = 'SET_SCROLLED_TO_TOP_SUCCESS';
export const UNSET_SCROLLED_TO_TOP_SUCCESS = 'UNSET_SCROLLED_TO_TOP_SUCCESS';
export const SET_SCROLLED_TO_BASIC_INFO_SUCCESS = 'SET_SCROLLED_TO_BASIC_INFO_SUCCESS';
export const UNSET_SCROLLED_TO_BASIC_INFO_SUCCESS = 'UNSET_SCROLLED_TO_BASIC_INFO_SUCCESS';
export const SET_SCROLLED_TO_EDUCATION_SUCCESS = 'SET_SCROLLED_TO_EDUCATION_SUCCESS';
export const UNSET_SCROLLED_TO_EDUCATION_SUCCESS = 'UNSET_SCROLLED_TO_EDUCATION_SUCCESS';
export const SET_SCROLLED_TO_SKILL_SET_SUCCESS = 'SET_SCROLLED_TO_SKILL_SET_SUCCESS';
export const UNSET_SCROLLED_TO_SKILL_SET_SUCCESS = 'UNSET_SCROLLED_TO_SKILL_SET_SUCCESS';
